module/actor/actor.js, module/item/item.js
This pull request to add custom hooks to facilitate the integration with automated animations (see https://github.com/otigon/automated-jb2a-animations/pull/38).
=> Custom hooks

module/demonlord.js
This pull request to add https://github.com/manuelVo/foundryvtt-drag-ruler integration
=> Drag ruler integration

module/item/item.js
This pull request to change the code to use the user target API instead of controlled tokens.
=> Refactoring to use targets instead of controlled tokens

module/demonlord.js
This pull request to penalty to speed when actor does not fulfill the strength requirement
=> Speed modifier on drag ruler

template.json, templates/actor/new-creature-sidemenu.html
This pull request to fix creature size
=> Fix creature size

src/module/item/action-template.js
This pull request to fix meaured template on Foundry 0.8.x
=> Fix measured template on 0.8.x

src/module/chat/chat-listeners.js, src/templates/chat/spell.html
This pull request to fix automated animations integration.
=> Fix automated animations integration

src/module/pixi/action-template.js, src/module/pixi/token-manager.js
This pull request to add selection support on creating measured templates.
=> Selection support on Measured Template

.eslintrc.js, src/module/active-effects/afflictions.js, src/module/active-effects/item-effects.js, src/module/actor/actor.js, src/module/actor/sheets/base-actor-sheet.js, src/module/chat/chat-listeners.js, src/module/chat/roll-messages.js, src/module/demonlord.js, src/module/item/item.js, src/module/item/nested-objects.js, src/module/item/sheets/base-item-sheet.js, src/module/migration.js, src/system.json
This pull request to add compatibility with foundry V9.
=> Foundry V9

src/module/actor/actor.js
Fix some Active Effects modes not being applied correctly.
=> Fix Active Effects

src/module/chat/roll-messages.js
Fix for several issues, mainly #115.
=> Fix some messages missing roll data

src/module/actor/actor.js, src/module/utils/handlebars-helpers.js, src/styles/components/actor-sheets/_aside-vehicle.scss, src/templates/actor/vehicle-sidemenu.hbs, src/templates/chat/talent.hbs, src/templates/tabs/creature-reference.hbs, src/templates/tabs/vehicle-reference.hbs
- Add default size to vehicles
- Add text field to vehicle size
- Round healing rate only once
- Fix missing attribute bonus in reference sheet
- Fix talent damage not rolling
=> Extra fixes

src/module/actor/actor.js
_onUpdateDescendantDocuments has a different signature than _onUpdateEmbeddedDocuments. Updated to match.
=> Urgent fix for non-updating actors

src/module/migration.js
Ignore locked compendia during migration.
=> 3.1.1 migration hotfix

src/lang/en.json, src/lang/es.json, src/module/active-effects/sheets/active-effect-config.js, src/module/actor/actor.js, src/module/chat/effect-messages.js, src/module/chat/roll-messages.js, src/module/demonlord.js, src/module/templates.js, src/styles/newrules/sheet-components.scss, src/templates/chat/combat.hbs, src/templates/chat/partial/chat-attack.hbs, src/templates/chat/partial/chat-description.hbs, src/templates/chat/spell.hbs, src/templates/chat/talent.hbs, src/templates/chat/useitem.hbs, src/templates/tabs/creature-view.hbs
- Add active effects for afflictions (`system.maluses.affliction`)
- Add active effects for Boon/Bane on all Attacks (`system.bonuses.attack.boons.all`) and Challenges (`system.bonuses.challenge.boons.all`)
- Add description to remaining items
- Remove duplicate "Attack Roll Bonus" from chat message
- Fix inline rolls clipping in creature reference tab
- Restore roll Special Action functionality
- Use enriched description for creature's Combat tab
=> Features and fixes

src/module/actor/actor.js
=> Hotfix 3.6.1

src/module/actor/sheets/base-actor-sheet.js, src/styles/components/actor-sheets/_aside-character.scss, src/templates/actor/sidemenu.hbs
- Prevents challange roll if character's attribute set to immune.
- Prevents the insanity/corruption change and hides actual/max values if they are set to immune.
=> Small actor sheet fixes

src/lang/en.json, src/module/utils/handlebars-helpers.js, src/templates/tabs/character.hbs, src/templates/tabs/creature-view.hbs, src/templates/tabs/magic.hbs, src/templates/tabs/talents.hbs
Nested items that are inherited from ancestry, path or creature role
=> Better visualization of nested items on actor sheets

src/lang/en.json, src/module/chat/base-messages.js, src/module/chat/roll-messages.js, src/module/settings.js
=> Add colour to used die on boons/banes (Dice So Nice!)

src/lang/en.json, src/module/chat/roll-messages.js, src/module/settings.js, src/templates/setting/optionalrules.hbs
page 215
_Certain attack talents take effect only if the creature gets a success on an attack roll total of 20 or higher and exceeds the target’s Defense by 5 or more._
Here's missing Extra Effect 20+
Here's one showing it has it
=> Fix above 20 result

src/lang/en.json, src/module/actor/actor.js, src/module/actor/sheets/character-sheet.js, src/module/chat/roll-messages.js, src/module/templates.js, src/styles/components/actor-sheets/_aside-character.scss, src/templates/actor/sidemenu.hbs, src/templates/chat/fortune.hbs
Right click -> Award a Fortune Point
Left click -> Expend a Fortune Point
Manual Input disabled
actor.expendFortune() function added
=> Make Fortune clickable  on character sheet

src/lang/en.json, src/module/actor/sheets/base-actor-sheet.js, src/module/demonlord.js, src/module/key-state.js, src/templates/tabs/item.hbs
While the CTRL key is down and clicking on an attribute a challenge roll will be done even a creature is targeted.
Containers on actor sheet.
=> Containers, ctrl+click on attirbute -> ChallengeRoll

src/lang/en.json, src/module/demonlord.js, src/module/settings.js
=> Option to set tokens automatically defeated in combat tracker

src/lang/en.json, src/module/actor/sheets/base-actor-sheet.js, src/module/actor/sheets/creature-sheet.js, src/module/settings.js, src/templates/actor/creature-sheet.hbs, src/templates/actor/creature-sidemenu.hbs, src/templates/actor/sidemenu.hbs, src/templates/tabs/item.hbs
Selecting non standard initiative method automatically hides TurnMode slider.
=> New options: Inventory for creatures, Hide Fortune on char sheets.

src/module/chat/effect-messages.js, src/module/chat/roll-messages.js, src/module/utils/key-state.js, src/module/utils/token-ruler.js
=> Chat card enhancement: added attribute modifier

src/module/data/common.js, src/templates/actor/parts/character-sheet-sidemenu.hbs, src/templates/actor/tabs/creature-combat.hbs
- Fix toggles editing wrong character sheet
- - Fix inability to edit lifestyle in character sheet
- Fix toggle info buttons in creature and vehicle sheets
=> Fixes after 5.1
