- src/module/actor/actor.js
- src/module/chat/chat-listeners.js
- src/module/demonlord.js
- src/module/item/item.js
- src/module/item/sheets/base-item-sheet.js
This pull request to add new hooks to automated animations integrations with others minors features/fixes.
> New hooks to automated animations

- src/module/chat/chat-listeners.js
- src/module/chat/roll-messages.js
Fixing an console error when `attackRoll` was not present in `postSpellToChat`. Added to other chat messages for safety.
> Only add rolls to chat message if one was present

- src/lang/pt-BR.json
- src/module/active-effects/effects.js
- src/module/active-effects/item-effects.js
- src/module/actor/actor.js
- src/module/chat/roll-messages.js
- src/module/demonlord.js
- src/templates/chat/spell.hbs
- src/templates/item/active-effect-config.hbs
- src/templates/item/item-talent-sheet.hbs
- src/templates/item/item-weapon-sheet.hbs
- src/templates/item/partial/item-effects.hbs
- src/templates/tabs/activeeffects.hbs
- Fix stuck delete on damage types (after main damage)
- Fall back to different damage values if main damage not present in talent
- Add 20+ damage box to talent and weapon
- Correctly hide 20+ damage on spell when not relevant
> Fixes and Features

- src/module/combat/combat.js
[Issue 212](https://github.com/Xacus/demonlord/issues/122) - Tested locally in the latest foundry.
> Fix for begin combat skipping first combatant

- src/module/demonlord.js
A fix for Disable Status Icons option not allowing damage apply equal or above token health due missing the "dead" condition.
Tested on Foundry V11.313
Did not find any issues related to this fix.
> Fix for Disable Status Icons option

- gulpfile.js
One of the two ways to fix the compendiums not having contents in 3.2.0
> updated path for compendium build output

- src/lang/en.json
- src/module/actor/actor.js
- src/module/actor/sheets/base-actor-sheet.js
- src/module/actor/sheets/character-sheet.js
- src/module/actor/token.js
- src/module/chat/chat-listeners.js
- src/module/chat/effect-messages.js
- src/module/chat/roll-messages.js
- src/module/demonlord.js
- src/module/dialog/endofround.js
- src/module/item/sheets/base-item-sheet.js
- src/module/macros/item-macros.js
- src/module/macros/player-macros.js
- src/module/utils/utils.js
- src/templates/dialogs/endofround-dialog.hbs
- Recolour damage bar (green to red as it fills up)
- Show roll modifiers individually
- Make roll evaluation async (future proof)
- Fix input boons not showing in chat message
- Enrich End of the Round dialog descriptions
- Restore extra damage from active effects on spells and items
- Small formatting improvements on chat messages
- Fix broken afflictions on non-English language
> More stuff

- src/module/active-effects/afflictions.js
- src/module/active-effects/effects.js
- src/module/active-effects/item-effects.js
- src/module/actor/actor.js
- src/module/actor/sheets/base-actor-sheet.js
- src/module/actor/sheets/character-sheet.js
- src/module/actor/sheets/creature-sheet.js
- src/module/chat/effect-messages.js
- src/module/chat/roll-messages.js
- src/module/combat/combat-tracker.js
- src/module/config.js
- src/module/demonlord.js
- src/module/item/item.js
- src/module/item/sheets/ancestry-sheet.js
- src/module/item/sheets/base-item-sheet.js
- src/module/item/sheets/path-sheet.js
- src/module/item/sheets/role-sheet.js
- src/module/macros/gm-macros.js
- src/module/macros/item-macros.js
- src/templates/actor/creature-header.hbs
- src/templates/actor/header.hbs
- src/templates/actor/vehicle-header.hbs
- src/templates/chat/combat.hbs
- src/templates/chat/partial/chat-attack.hbs
- src/templates/chat/partial/chat-damage.hbs
- src/templates/item/partial/item-effects.hbs
- Normalise appearance of attack messages and damage buttons across item types
- Allow 20 plus damage from multiple sources (e.g. talent and active effect)
- Support active effects that affect size
- Hide modifier label for immune attributes
- Move to modern effect transferral mode
- Fix broken square measured templates
- Add default image for relics
- Remove references to deprecated `data`
- Don't break when combat has null actors
> Attack message normalisation

- src/templates/tabs/creature-reference.hbs
If the creature has no attack option, the following information also not displayed on the creature reference screen
- Special Attacks
- Special Actions
- End of the Round
> Details are missing on the creature reference screen in some cases

- src/templates/tabs/item.hbs
If an item is a container, the number of items in it is displayed in round brackets after its name.
> Displaying then number of items in container-items.

- src/lang/en.json
- src/lang/fr.json
- src/module/actor/actor.js
- src/module/chat/effect-messages.js
- src/module/settings.js
Automatically add 1 bane on attack rolls targeting a horrifying creature if the attacker lacks the frightening or horrifying trait.
Can be disabled in the settings.
> Banes on attack rolls against horrifying creatures

- src/module/actor/actor.js
Advancing world time during rest automatically means world time will advance multiple times when several characters rest simultaneously.
Also, world time advance triggers a permission error for players depending on the permission configuration in the world.
> Fix: remove world time advance from rest

- src/module/chat/base-messages.js
Colour markup added to the highest boons/banes die in the chat window tooltip.
> Chat card tooltip tweak

- src/module/actor/actor.js
Unfortunately each action deletes NextD20Roll effects even the key was not used. E.g. attack roll deletes effects with key "system.bonuses.challenge.boons*" and vice versa.
With this fix:
The following actions deletes NextD20Roll effects where key contains "system.bonuses.attack.boons*"
1. Attack with a weapon
2. End Of The Round
3. Talent/Specfial Attacks 
4. Casting a spell
Challenge roll deletes NextD20Roll effects where key contains "system.bonuses.challenge.boons*"
> NextD20Roll effect deletion fix

- src/lang/en.json
- src/module/active-effects/effects.js
- src/module/actor/actor.js
- src/module/chat/chat-listeners.js
- src/module/combat/combat.js
Added: New special duration: RestComplete
Fixed: Incorrect effect name, when applying effect on multiple target.
Fixed: EndOfTheRound ignores system.bonuses.attack.boons.attribute.
Fixed: NextD20Roll ignores system.bonuses.attack.boons.attribute, system.bonuses.attack.boons.weapon and system.bonuses.attack.boons.spell on deletion.
> New special duration: RestComplete, NextD20Roll deletion fixes, Effect name fix

- src/lang/en.json
- src/module/chat/base-messages.js
- src/module/demonlord.js
- src/module/settings.js
Added: Option to hide actor info from chat messages for non-owned actors.
Fixed: Actor info does not contain path description
> Option to hide actor info from chat messages

- src/lang/en.json
- src/module/actor/actor.js
- src/module/settings.js
- src/templates/setting/optionalrules.hbs
Added:
* [Somniac Delusions' rule:](https://somniacdelusions.wordpress.com/2019/04/17/sotdl-house-rules/) Creatures lose their frightening or horrifying traits for characters of a certain level or higher, according to the creature’s difficulty. 
Modified
* "Bane against horrifying creatures" option moved to Optional Rules settings
Fix
* DL.SettingOptinalRuleExceedsByFiveHint not displayed
> Creatures lose their frightening or horrifying traits for characters of a certain level or higher, according to the creature’s difficulty.

- src/lang/en.json
- src/module/demonlord.js
- src/module/settings.js
- src/templates/chat/partial/chat-description.hbs
> Option to show/hide creature activity descriptions

- src/module/actor/actor.js
Spells with "Attack" type have an extra dialog where you can select boons/bane. This dialog does not appear when using non-English locale.
Internal logic for this uses comparison of `item.system.spelltype` to localized string of spell type. In case of Spanish, for example, this means `"Attack" === "Ataque"`, which is always false.
I'm not sure what was the original intent with using a localized string there, but changing this condition to use "Attack" constant seem to solve the issue for me.
> Fix boon/bane dialog for attack spells when using non-English locale

- src/lang/en.json
- src/module/actor/actor.js
- src/module/chat/effect-messages.js
- src/module/chat/roll-messages.js
- src/module/settings.js
> Option to hide damage/effect buttons from chat messages when attack roll fails.
